version: "2.1"
services:
    restore_test:
        build:
            context: .
            dockerfile: Dockerfile-odoobak
        image: filament/duplicity:postgres
        hostname: backup-odoo
        domainname: "docker.le-filament.com"
        environment:
            DST: "swift://odoo_{{ inventory_hostname|lower }}"
            PGDATABASE: "{{ odoo_db_test }}"
            PGUSER: "{{ odoo_db_user }}"
            PGPASSWORD: "{{ odoo_db_pass }}"
            PASSPHRASE: "{{ odoo_master_pass }}"
            SWIFT_USERNAME: "{{ swift_odoo_username }}"
            SWIFT_PASSWORD: "{{ swift_odoo_password }}"
            SWIFT_AUTHURL: "{{ swift_odoo_authurl }}"
            SWIFT_AUTHVERSION: {{ swift_odoo_authversion }}
            SWIFT_TENANTNAME: "{{ swift_odoo_tenantname }}"
            SWIFT_TENANTID: "{{ swift_odoo_tenantid }}"
            SWIFT_REGIONNAME: "{{ swift_odoo_regionname }}"
            OPTIONS: "--force"
        volumes:
            - odootest_filestore:/mnt/backup/src/odoo:z
        networks:
            - odootest_default
            - public
        command: [sh, -c, "restore && mv /mnt/backup/src/odoo/filestore/{{ odoo_db }} /mnt/backup/src/odoo/filestore/$$PGDATABASE && createdb -T template0 $$PGDATABASE && pg_restore -d $$PGDATABASE $$SRC/{{ odoo_db }}.pgdump"]

networks:
    odootest_default:
        driver_opts:
            encrypted: 1
        external: true
    public:
        driver_opts:
            encrypted: 1

volumes:
    odootest_filestore:
        external: true
